.*: Assembler messages:
.*: Error: internal: invalid scale value 3 for decbnez. Scale must be 1, 2, 4, 8. 
.*: Error: illegal operands `decbnez s2,3,1'
.*: Error: internal: invalid scale value 0 for decbnez. Scale must be 1, 2, 4, 8. 
.*: Error: illegal operands `decbnez s2,0,1'
.*: Error: internal: invalid scale value 0 for c.decbnez. Scale must be 1, 2, 4, 8. 
.*: Error: illegal operands `c.decbnez a5,0,1'
.*: Error: internal: invalid scale value 9 for c.decbnez. Scale must be 1, 2, 4, 8. 
.*: Error: illegal operands `c.decbnez a5,9,1'
